### ISSUE TITLE
Bug: Failed Image Upload

### ISSUE THREAD

**Issue by houshasen** [dhofstedt/pqi-mvp#13]
https://radshare.net/ultimateCases/3

I tried to attach total 4 images in this case.  All by using copy & paste.

One on Image section.
One on Finding section
Two on Discussion section

From the original creation of case to submission, there were significant time lapse ~30+ min. But otherwise, pasting images looked fine before submission.

However, after submission no images looked to have uploaded.

**Comment by dhofstedt** [comment]
My suspicion is that the image was too big. Working on a solution to maintain the easy copy paste functionality but also allow larger images to be uploaded. Courrently the images are stored directly into the DB as a blob, and there is a limit to the blob size, TinyMCE, the WYSIWYG editor used, has the ability to have images pasted in to be stored as a path to a separate file, which should free up the current cap on blob size and allow larger images to be pasted in. For now, using smaller images for cases is the suboptimal but functional workaround.

**Comment by houshasen** [comment]
I’d be curious if the size limit. Screen capture shouldn’t be that big of size.

iPhoneから送信

**Comment by dhofstedt** [comment]
The data is not that big, but right now the images are being stored in an img tag with the src as a giant string that onece the character limit is reached the img tag is unfinished, messing up all of the html after it.

[This page](https://www.tiny.cloud/docs/general-configuration-guide/upload-images/) from the timyMCE has the soulution to the problem, storing the src as a path to the image in a remote file rather than a super long Base64 string.

The part that I think points out the problem:
> Local images are uploaded to TinyMCE using the editor.uploadImages() function. This functionality makes it possible for users to save their content before all images have completed uploading. _If this occurs and no server path to the remote image is available, the images are saved as Base64._

Right now, no server path to the remote image is written but I will change that hopefully by following the steps in the tinyMCE documentation.

**Comment by houshasen** [comment]
That makes total sense.

Now, with current method of data storage, do we have a way to backup/restore all data?

**Comment by dhofstedt** [comment]
Good question. Yes, we can backup and restore the database if we need to.

**Comment by houshasen** [comment]
Cool. Eventually, we should consider formal scheduled backup as content would be the highest value here.

iPhoneから送信

**Comment by dhofstedt** [comment]
Image upload problem fixed. Now the images are stored in a folder and saved in the database as a path to the file. Now there should be no practical limit to the size and number of images you can upload. I just submitted an acute appendicitis case with three large images and it works great!

The only caveat, the images to not upload immediately when pasted in. The upload feature of the wysiwyg editor needs to be used, but that doesn't add too much difficulty. I know it is possible for the image to upload immediately upon pasting, but for now it will do the way it is.
