### ISSUE TITLE
Suggestion: Default Dark Background

### ISSUE THREAD

**Issue by houshasen** [dhofstedt/pqi-mvp#5]
Given most typical situation for the site access is in the dark reading room, dark e.g. black background as a default may be better on the eyes.

For the future as added feature, perhaps dark/light mode switching option and retaining such setting at user account level may be a nice little addition though very low on priority.

**Comment by dhofstedt** [comment]
Dark mode implemented locally. Looks like this:

![image](https://user-images.githubusercontent.com/20133294/124536727-17ff0800-ddde-11eb-87d7-b218e8c5bc79.png)

and this:

![image](https://user-images.githubusercontent.com/20133294/124536779-36650380-ddde-11eb-9097-a7fceef198ba.png)

**Comment by houshasen** [comment]
Looks good to me.

iPhoneから送信
