### ISSUE TITLE
Bug: Editing submitted case is not working

### ISSUE THREAD

**Issue by houshasen** [dhofstedt/pqi-mvp#6]
User who have submitted a case should have edit capability. Currently, this option is not available.

**Comment by dhofstedt** [comment]
Edit button added to the show case view underneath the exit button. Only visible to the case author. The edit route is also protected to only be accessible to the author. 

![image](https://user-images.githubusercontent.com/20133294/128267415-0fdcbf15-29f2-453f-a888-2a2ba254511f.png)
